name: Intégration continue et déploiement continue
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Node
      uses: actions/setup-node@v3
      with:
        node-version: '20'
    - name: Mise a jour du node modules
      run: npm install
    - name: Java 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11' # -_______________-
    - name: Build apk
      run: cd android && ./gradlew assembleRelease
    - name: envoie de apk
      uses: easingthemes/ssh-deploy@v2.1.5
      env:
        SSH_PRIVATE_KEY: ${{ secrets.KEY }}
        SOURCE: "android/app/build/outputs/apk/release/"
        REMOTE_HOST: ${{ secrets.HOST }}
        REMOTE_USER: ${{ secrets.USER }}
        REMOTE_PORT: "22"
        TARGET: "~/home/theo/mobile/$(date +'%Y-%m-%d-%H-%M')" 