name: Intégration continue et déploiement continue
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Node
      uses: actions/setup-node@v3
      with:
        node-version: '20'
    - name: Mise a jour du node modules
      run: |
        npm install
        npm i -g corepack
    - name: Java 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11' # -_______________-
        cache: "gradle"
    - name: ls
      run: ls
    - name: Gradle
      uses: gradle/gradle-build-action@v2
      with:
        distribution: 'jdk11'
        version: '7.0.2'
    - run : ls
    - name: Config de la clé private via création d'un fichier + injection
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.KEY  }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
    - run: ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -T theo@51.178.30.100 "ls"
    - name: Mise en place du SSH agent (car scp ne fonctionne pas sans)
      uses: webfactory/ssh-agent@v0.5.0
      with:
        ssh-private-key: ${{ secrets.KEY }}
    - name: Création du dossier avec la date + transfert du document
      run: scp -r -o StrictHostKeyChecking=no App.js ${{ secrets.USER }}@${{ secrets.HOST }}:/home/theo/mobile/$(date +"%Y-%m-%d-%H-%M")